export PATH="$PATH:$HOME/.local/bin:/snap/bin"
export CONFIG_PATH="$HOME/.config/zsh"
export JAVA_HOME=$(dirname $(dirname $(readlink -f $(which javac)))) 

source $CONFIG_PATH/aliases.zsh
source $CONFIG_PATH/vim_bindings.zsh
source $CONFIG_PATH/long_history.zsh
source $CONFIG_PATH/fzf_setup.zsh
source $CONFIG_PATH/beautiful_spinner.zsh
source $CONFIG_PATH/tools.zsh
source $CONFIG_PATH/tmux_connect.zsh
